### ISSUE TITLE
Update to latest tower-lsp

### ISSUE THREAD

**Issue by ebkalderon** [wayfair-tremor/tremor-language-server#5]
Author of `tower-lsp` here! I just wanted to let you know that `tower-lsp` has been rapidly improving over the past several months and has seen a great many improvements since 0.4.1. Among other things, it has gained:

* Support for `std::future::Future`, the newest `tokio`, and async/await.
* Support for a crap-ton more LSP requests, [almost supporting all of LSP 3.15](https://github.com/ebkalderon/tower-lsp/issues/10).
* Support for all server-to-client requests, renaming `Printer` to [`Client`](https://docs.rs/tower-lsp/0.9.0/tower_lsp/struct.Client.html).
* `LanguageServer` trait methods are no longer required, except for `initialize` and `shutdown`.
* Notification trait methods are now `async fn`.
* You can now call `.await` on `serve()` directly, eliminating the need for `ExitReceiver`.
* Backpressure is now handled properly.

If you would like to port your server to async/await and add some new features to your language server, such as goto declaration, goto definition, goto type definition, code formatting, document symbols, references, etc. [0.9.0 has just been published to Crates.io](https://crates.io/crates/tower-lsp).

Not exactly sure if this announcement requires an official library RFC as per the contributing guidelines, but if it does, I do sincerely apologize for submitting this suggestion out of form. Feel free to close this issue if that is the case!

**Comment by darach** [comment]
Hi Eyal,

Oh that's great to know! Thank you for tower-lsp - we get a lot of benefit from it and its a great way to write language servers in rust. These looks like a really nice set of changes and we're sure to upgrade soon!

Cheers,

Darach.

**Comment by Licenser** [comment]
That's awesome :) thanks for `tower-lsp` it has saved us quite some work! The move to async is great news, we are in the progress to adopting it and it'll be nice to pull it in the language server, again thanks for the great work!

**Comment by ebkalderon** [comment]
Thanks for the kind words, @darach and @Licenser. Both Tremor and the language server project look awesome! I'm happy that you found `tower-lsp` useful to you, and I hope you haven't been blocked by anything on my end. Feel free to report any blockers or bugs you find with it, and I'll try my best to respond to them.
